#:kivy 1.4.1

<BallsContainer>:
    canvas:
        Color:
            rgb: 0.2, 0.2, 0.2
        Rectangle:
            pos: self.pos
            size: self.size
    Label:
        color: 0, 0, 0, 1
        top: root.top
        font_size: 36
        text: str(len(root.children) - 1)


<Ball>:
    size: 100, 100
    canvas:
        Color:
            rgba: self.col
        Ellipse:
            pos: self.pos
            size: self.size
